<nav class="flex flex-wrap gap-2 rounded-2xl border bg-white p-3 text-sm">
    <a href="<?php echo e(route('admin.crm.dashboard')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.crm.dashboard') ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700'); ?>">لوحة CRM</a>
    <a href="<?php echo e(route('admin.crm.leads.index')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.crm.leads.*') ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-700'); ?>">العملاء المحتملون</a>
    <a href="<?php echo e(route('admin.crm.commissions.index')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.crm.commissions.*') ? 'bg-violet-600 text-white' : 'bg-slate-100 text-slate-700'); ?>">العمولات</a>
    <a href="<?php echo e(route('admin.crm.audit.index')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.crm.audit.*') ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-700'); ?>">سجل المتابعة</a>
    <a href="<?php echo e(route('admin.crm.groups.index')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.crm.groups.*') ? 'bg-sky-600 text-white' : 'bg-slate-100 text-slate-700'); ?>">مجموعات الفريق</a>
    <a href="<?php echo e(route('admin.crm.reports.index')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.crm.reports.*') ? 'bg-rose-600 text-white' : 'bg-slate-100 text-slate-700'); ?>">تقارير CRM</a>
    <a href="<?php echo e(route('admin.employee-jobs.index')); ?>" class="px-3 py-1.5 rounded-lg font-bold <?php echo e(request()->routeIs('admin.employee-jobs.*') ? 'bg-cyan-600 text-white' : 'bg-slate-100 text-slate-700'); ?>">صلاحيات الوظائف</a>
</nav>
<?php /**PATH C:\xampp\htdocs\glottical\resources\views/partials/crm-admin-nav.blade.php ENDPATH**/ ?>